import { SpongeLocation } from "./types";

export const spongeLocations: SpongeLocation[] = [
  {
    id: 0,
    name: "Analyzing Toronto...",
    coordinates: [43.6536, -79.3877],
    description: "Finding location data...",
    score: "",
    benefits: [
      "Calculating benefits...",
      "Analyzing environmental impact...",
      "Assessing community value...",
      "Evaluating infrastructure...",
    ],
    imageUrl: "https://images.pexels.com/photos/374870/pexels-photo-374870.jpeg?cs=srgb&dl=pexels-burst-374870.jpg&fm=jpg",
    ownership: "analyzing",
    zoning: "analyzing",
    population: 0,
    budget: 0,
  },
  {
    id: 1,
    name: "Grange Park",
    coordinates: [43.6536, -79.3877],
    description:
      "Recently revitalized park adjacent to the Art Gallery of Ontario, featuring contemporary design with water features and mature tree canopy.",
    score: 8.7,
    benefits: [
      "Urban cooling",
      "Arts and cultural integration",
      "Community gathering space",
      "Stormwater management",
    ],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Grange_Park_Lawn_2023.JPG",
    ownership: "government",
    zoning: "green-space",
    population: 35000,
    budget: 3200000,
  },
  {
    id: 2,
    name: "Berczy Park",
    coordinates: [43.6485, -79.3741],
    description:
      "Charming urban park with a whimsical dog fountain, providing a green oasis amid the Financial District and St. Lawrence neighborhood.",
    score: 8.3,
    benefits: [
      "Microclimate regulation",
      "Tourism attraction",
      "Public art showcase",
      "Urban beautification",
    ],
    imageUrl: "https://www.citywindsor.ca/images/residents/parks-and-forestry/city-parks/assumption%20park%20street%20view.jpg",
    ownership: "government",
    zoning: "green-space",
    population: 25000,
    budget: 2700000,
  },
  {
    id: 3,
    name: "Corktown Common",
    coordinates: [43.6542, -79.3566],
    description:
      "Award-winning park in the West Don Lands featuring wetlands, lawns, urban prairies, and a marsh that serves as natural stormwater management.",
    score: 9.1,
    benefits: [
      "Flood protection",
      "Ecological restoration",
      "Community recreation",
      "Sustainable water management",
    ],
    imageUrl: "https://www.citywindsor.ca/images/residents/parks-and-forestry/city-parks/assumption%20park%20street%20view.jpg",
    ownership: "government",
    zoning: "green-space",
    population: 20000,
    budget: 4100000,
  },
  {
    id: 4,
    name: "David Crombie Park",
    coordinates: [43.6509, -79.3677],
    description:
      "Linear park connecting the St. Lawrence neighborhood with potential for enhanced green infrastructure and water management features.",
    score: 7.9,
    benefits: [
      "Green corridor connectivity",
      "Pedestrian-friendly spaces",
      "Neighborhood cohesion",
      "Urban wildlife support",
    ],
    imageUrl: "https://www.citywindsor.ca/images/residents/parks-and-forestry/city-parks/assumption%20park%20street%20view.jpg",
    ownership: "private",
    zoning: "green-space",
    population: 18000,
    budget: 2500000,
  },
  {
    id: 5,
    name: "Moss Park",
    coordinates: [43.6553, -79.3752],
    description:
      "Centrally located park serving diverse communities with significant potential for green infrastructure improvements and social inclusion.",
    score: 8.2,
    benefits: [
      "Social equity enhancement",
      "Urban cooling",
      "Community engagement",
      "Recreational opportunities",
    ],
    imageUrl: "https://www.citywindsor.ca/images/residents/parks-and-forestry/city-parks/assumption%20park%20street%20view.jpg",
    ownership: "government",
    zoning: "green-space",
    population: 30000,
    budget: 3300000,
  },
  {
    id: 6,
    name: "Allan Gardens",
    coordinates: [43.6613, -79.3733],
    description:
      "Historic park featuring Victorian-era palm house and conservatory with potential for expanded green infrastructure and climate adaptation.",
    score: 8.8,
    benefits: [
      "Heritage preservation",
      "Botanical diversity",
      "Educational programming",
      "Microclimate regulation",
    ],
    imageUrl: "https://www.citywindsor.ca/images/residents/parks-and-forestry/city-parks/assumption%20park%20street%20view.jpg",
    ownership: "government",
    zoning: "green-space",
    population: 22000,
    budget: 3000000,
  },
  {
    id: 7,
    name: "St. James Park",
    coordinates: [43.6518, -79.3724],
    description:
      "Elegant Victorian-style park surrounding St. James Cathedral with mature trees and ornamental gardens ideal for green infrastructure enhancement.",
    score: 7.8,
    benefits: [
      "Heritage integration",
      "Air quality improvement",
      "Urban cooling",
      "Community wellbeing",
    ],
    imageUrl: "https://www.citywindsor.ca/images/residents/parks-and-forestry/city-parks/assumption%20park%20street%20view.jpg",
    ownership: "private",
    zoning: "green-space",
    population: 15000,
    budget: 2200000,
  },
  {
    id: 8,
    name: "Bellevue Square Park",
    coordinates: [43.6486, -79.4019],
    description:
      "Kensington Market's central park with community gardens and gathering spaces supporting diverse cultural activities.",
    score: 8.5,
    benefits: [
      "Cultural diversity support",
      "Community gardening",
      "Urban heat mitigation",
      "Public engagement",
    ],
    imageUrl: "https://images.squarespace-cdn.com/content/v1/5ccf4dc4b914495805680958/1564084168750-9MVFATS3P09VSOWACBS3/TPP_Website_BellevueSquare3.jpg",
    ownership: "government",
    zoning: "green-space",
    population: 28000,
    budget: 2800000,
  },
  {
    id: 9,
    name: "Roundhouse Park",
    coordinates: [43.6416, -79.3841],
    description:
      "Historical railway-themed park adjacent to the CN Tower and Rogers Centre featuring the Toronto Railway Museum.",
    score: 7.6,
    benefits: [
      "Industrial heritage preservation",
      "Tourism enhancement",
      "Urban cooling",
      "Stormwater capture",
    ],
    imageUrl: "https://www.citywindsor.ca/images/residents/parks-and-forestry/city-parks/assumption%20park%20street%20view.jpg",
    ownership: "private",
    zoning: "green-space",
    population: 20000,
    budget: 2400000,
  },
  {
    id: 10,
    name: "Regent Park",
    coordinates: [43.6607, -79.3675],
    description:
      "Recently revitalized community park as part of the neighborhood redevelopment, featuring contemporary design and community facilities.",
    score: 8.9,
    benefits: [
      "Social equity promotion",
      "Community cohesion",
      "Recreation access",
      "Green infrastructure",
    ],
    imageUrl: "https://www.citywindsor.ca/images/residents/parks-and-forestry/city-parks/assumption%20park%20street%20view.jpg",
    ownership: "private",
    zoning: "green-space",
    population: 27000,
    budget: 3600000,
  },
  {
    id: 11,
    name: "Harbourfront Music Garden",
    coordinates: [43.6366, -79.3944],
    description:
      "Waterfront garden inspired by Bach's First Suite for Unaccompanied Cello, featuring themed sections and lakeshore views.",
    score: 8.6,
    benefits: [
      "Cultural expression",
      "Waterfront enhancement",
      "Tourism attraction",
      "Biodiversity support",
    ],
    imageUrl: "https://www.citywindsor.ca/images/residents/parks-and-forestry/city-parks/assumption%20park%20street%20view.jpg",
    ownership: "private",
    zoning: "green-space",
    population: 18000,
    budget: 3100000,
  },
  {
    id: 12,
    name: "HTO Park",
    coordinates: [43.6382, -79.3898],
    description:
      "Urban beach park on the waterfront with distinctive yellow umbrellas and sandy areas designed for relaxation and lake viewing.",
    score: 8.1,
    benefits: [
      "Waterfront access",
      "Recreation opportunity",
      "Tourism enhancement",
      "Microclimate regulation",
    ],
    imageUrl: "https://www.citywindsor.ca/images/residents/parks-and-forestry/city-parks/assumption%20park%20street%20view.jpg",
    ownership: "government",
    zoning: "green-space",
    population: 22000,
    budget: 2600000,
  },
  {
    id: 13,
    name: "Little Norway Park",
    coordinates: [43.637, -79.3985],
    description:
      "Waterfront park commemorating Norwegian air force training during WWII, offering green space among dense urban development.",
    score: 7.5,
    benefits: [
      "Historical significance",
      "Urban cooling",
      "Community recreation",
      "Stormwater management",
    ],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7f/Little_Norway_Park.jpg",
    ownership: "government",
    zoning: "green-space",
    population: 16000,
    budget: 2300000,
  },
  {
    id: 14,
    name: "Barbara Hall Park",
    coordinates: [43.6652, -79.38],
    description:
      "Community park in the Church-Wellesley Village featuring the 519 Community Centre and LGBTQ+ community programming.",
    score: 7.9,
    benefits: [
      "Social inclusion",
      "Community engagement",
      "Urban greening",
      "Recreation access",
    ],
    imageUrl: "https://www.citywindsor.ca/images/residents/parks-and-forestry/city-parks/assumption%20park%20street%20view.jpg",
    ownership: "government",
    zoning: "green-space",
    population: 25000,
    budget: 2400000,
  },
  {
    id: 15,
    name: "Canoe Landing Park",
    coordinates: [43.6396, -79.3959],
    description:
      "Contemporary urban park with large-scale public art including a red canoe overlooking the Gardiner Expressway.",
    score: 8.7,
    benefits: [
      "Public art integration",
      "Recreation facilities",
      "Urban heat reduction",
      "Community gathering",
    ],
    imageUrl: "https://www.citywindsor.ca/images/residents/parks-and-forestry/city-parks/assumption%20park%20street%20view.jpg",
    ownership: "government",
    zoning: "green-space",
    population: 30000,
    budget: 3700000,
  },
  {
    id: 16,
    name: "Cloud Gardens",
    coordinates: [43.6483, -79.3791],
    description:
      "Small downtown park featuring a greenhouse and waterfall, providing a compact urban oasis amid office towers.",
    score: 7.4,
    benefits: [
      "Microclimate regulation",
      "Office district amenity",
      "Urban biodiversity",
      "Mental health benefits",
    ],
    imageUrl: "https://www.citywindsor.ca/images/residents/parks-and-forestry/city-parks/assumption%20park%20street%20view.jpg",
    ownership: "government",
    zoning: "green-space",
    population: 12000,
    budget: 1900000,
  },
  {
    id: 17,
    name: "Underpass Park",
    coordinates: [43.6551, -79.3572],
    description:
      "Innovative park created beneath the Eastern Avenue and Richmond/Adelaide overpasses, transforming underutilized space with skate features and public art.",
    score: 8.4,
    benefits: [
      "Urban space reclamation",
      "Youth engagement",
      "Public art showcase",
      "Infrastructure integration",
    ],
    imageUrl: "https://www.citywindsor.ca/images/residents/parks-and-forestry/city-parks/assumption%20park%20street%20view.jpg",
    ownership: "government",
    zoning: "green-space",
    population: 15000,
    budget: 2900000,
  },
  {
    id: 18,
    name: "Clarence Square",
    coordinates: [43.6447, -79.3911],
    description:
      "Historic park with mature trees providing a green oasis within the King West neighborhood.",
    score: 7.7,
    benefits: [
      "Heritage value",
      "Urban canopy preservation",
      "Heat island mitigation",
      "Community space",
    ],
    imageUrl: "https://www.citywindsor.ca/images/residents/parks-and-forestry/city-parks/assumption%20park%20street%20view.jpg",
    ownership: "government",
    zoning: "green-space",
    population: 18000,
    budget: 2100000,
  },
  {
    id: 19,
    name: "Victoria Memorial Square",
    coordinates: [43.6428, -79.398],
    description:
      "One of Toronto's oldest parks and first military burial grounds, now a commemorative space with heritage significance.",
    score: 7.6,
    benefits: [
      "Historical preservation",
      "Urban cooling",
      "Community connection",
      "Cultural heritage",
    ],
    imageUrl: "https://www.citywindsor.ca/images/residents/parks-and-forestry/city-parks/assumption%20park%20street%20view.jpg",
    ownership: "government",
    zoning: "green-space",
    population: 14000,
    budget: 2000000,
  },
  {
    id: 20,
    name: "Sugar Beach",
    coordinates: [43.6414, -79.3692],
    description:
      "Whimsical urban beach park with signature pink umbrellas adjacent to the old Redpath Sugar Factory, blending industrial history with leisure space.",
    score: 8.9,
    benefits: [
      "Waterfront activation",
      "Tourism draw",
      "Urban design innovation",
      "Public relaxation space",
    ],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/58/SugarBeach9.jpg",
    ownership: "government",
    zoning: "green-space",
    population: 20000,
    budget: 3400000,
  },
];
